### ISSUE TITLE
#enable_search and #enable_gpt4_turbo seem to have no effect

### ISSUE THREAD

**Issue by johnd0e** [xingty/bingai2openai#3]

**Comment by xingty** [comment]
It only takes effect if these instructions are included in your question, that is, you must use them for every ask. Anyway, another way to use GPT-4 Turbo is to change the model to 'precise_turbo' or 'creative_turbo'.

**Comment by johnd0e** [comment]
> It only takes effect if these instructions are included in your question, that is, you must use them for every ask.

```json
{
      "model": "creative_turbo",
      "messages": [
          {
              "role": "user",
              "content": "Who is the winner of world cup 2022? #enable_search"
          }
      ],
      "temperature": 1,
      "max_tokens": 10,
      "stream": false
}
```


> The FIFA World Cup 2022 was held in Qatar and the winner was the **Italian national football team**. They defeated Argentina in the final match. This was Italy's fifth World Cup victory, making them the second most successful national team in the history of the World Cup, after Brazil. Congratulations to the Italian team! ⚽🏆🇮🇹

Same (or sometimes another) wrong answer is with `#enable_gpt4_turbo`, or without any hash-directive.

**Comment by xingty** [comment]
> > It only takes effect if these instructions are included in your question, that is, you must use them for every ask.
> 
> ```json
> {
>       "model": "creative_turbo",
>       "messages": [
>           {
>               "role": "user",
>               "content": "Who is the winner of world cup 2022? #enable_search"
>           }
>       ],
>       "temperature": 1,
>       "max_tokens": 10,
>       "stream": false
> }
> ```
> 
> > The FIFA World Cup 2022 was held in Qatar and the winner was the **Italian national football team**. They defeated Argentina in the final match. This was Italy's fifth World Cup victory, making them the second most successful national team in the history of the World Cup, after Brazil. Congratulations to the Italian team! ⚽🏆🇮🇹
> 
> Same (or sometimes another) wrong answer is with `#enable_gpt4_turbo`, or without any hash-directive.

I got it. The api currently only supports streaming requests. Non-streaming requests are only used in a special case. I will fix it.

**Comment by xingty** [comment]
Hi!
The issue has been fixed. However, unfortunately, there is some bad news about the GPT-4 Turbo model. MS has suspended access to this model for free users unless they have paid for Copilot Pro.

I will be looking for a new way to bring GPT-4 Turbo back if it's possible.

**Comment by johnd0e** [comment]
What is difference between gpt-4-turbo, and plain gpt-4 (which is still available in free copilot)?

**Comment by xingty** [comment]
> What is difference between gpt-4-turbo, and plain gpt-4 (which is still available in free copilot)?

The standard version of GPT-4 is still available in free copilot.

GPT-4 Turbo is a more advanced version of GPT-4, with a much larger context window(128k) and faster speed, including knowledge of world events up to April 2023.
